name: Love Returns
favicon: null
layout_spectrum: 0.1765957
typography_spectrum: 0.5166
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#07060C'
    - '#DFE1E0'
    - '#435390'
    - '#FF7E55'
    - '#FA8901'
  brandStrength: 0.5
  lightness: 0.3744681
  saturation: 1
  rhythmicContrast: 0.7007521
purpose: []
